# Asignar puerto dinamico interno de comunicacion, para poder trabajar con el API
server:
  port: ${PORT:0}
  error:
    include-message: always

# EUREKA CUSTOMER
eureka:
  instance:
    # nombres internos dinámicos para conectarse con eureka
    instance-id: ${spring-application-name}:${random-value}
  client:
    service-url:
      # URL del servidor Eureka al que el cliente debe conectarse para registrarse y buscar otros servicios
      defaultZone: http://localhost:8761/eureka

# DB MONGO
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: mscustomerdb
#      repositories:
#        enabled: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring:
  data:
    mongodb:
      uri: mongodb+srv://neosapiens8:123456sql@cluster0.hkerxlh.mongodb.net/
      database: mscustomerdb1
      repositories:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
